reports:
  exclude_paths:
    - contracts/testing/*.*

networks:
  development:
    cmd_settings:
      accounts: 100
  mainnet-fork:
    cmd_settings:
      unlock: 0xC447FcAF1dEf19A583F97b3620627BF69c05b5fB

autofetch_sources: True
dependencies:
  - curvefi/curve-crypto-contract@1.0.0
  - OpenZeppelin/openzeppelin-contracts@3.4.0
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dev_deployment_artifacts: true

compiler:
  solc:
    version: "0.8.0"
    optimizer:
      enabled: true
      runs: 200
    vyper:
      version: "0.3.1"
